#!/usr/bin/env python3
"""
gen_configs.py — VibeRTOS Kconfig output generator.

Uses kconfiglib to load the full Kconfig tree, optionally apply a board
defconfig, and emit four output files:

  autoconf.h       — C header  (#define CONFIG_FOO 1)
  sdkconfig        — Kconfig .config file  (CONFIG_FOO=y)
  sdkconfig.cmake  — CMake variables       (set(CONFIG_FOO 1))
  sdkconfig.json   — JSON object           {"CONFIG_FOO": true}

Usage:
  python gen_configs.py \\
      --kconfig  <root>/Kconfig \\
      --config   <build>/sdkconfig \\
      --header   <build>/include/generated/autoconf.h \\
      --cmake    <build>/sdkconfig.cmake \\
      --json     <build>/sdkconfig.json \\
      --srctree  <root> \\
      [--board-defconfig <board>/<board>_defconfig]
"""

import argparse
import json
import os
import sys
try:
    import kconfiglib
except ImportError:
    print(
        "ERROR: kconfiglib is not installed.\n"
        "       Install it with:  pip install kconfiglib",
        file=sys.stderr,
    )
    sys.exit(1)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ensure_dir(path):
    d = os.path.dirname(path)
    if d:
        os.makedirs(d, exist_ok=True)


def write_autoconf(kconf, path):
    """Write autoconf.h via kconfiglib's built-in method."""
    _ensure_dir(path)
    kconf.write_autoconf(path)


def write_sdkconfig(kconf, path):
    """Write .config / sdkconfig file."""
    _ensure_dir(path)
    kconf.write_config(path)


def write_cmake(kconf, path):
    """Write sdkconfig.cmake with set(CONFIG_<NAME> <value>) lines."""
    
    _ensure_dir(path)
    lines = [
        "# Auto-generated by gen_configs.py — do not edit\n",
        "# Include this file to get CONFIG_* CMake variables.\n\n",
    ]
    for sym in kconf.unique_defined_syms:
        name = f"CONFIG_{sym.name}"
        if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
            val = "1" if sym.str_value == "y" else "0"
            lines.append(f"set({name} {val})\n")
        elif sym.type == kconfiglib.INT:
            lines.append(f"set({name} {sym.str_value})\n")
        elif sym.type == kconfiglib.HEX:
            lines.append(f"set({name} {sym.str_value})\n")
        elif sym.type == kconfiglib.STRING:
            # Escape backslashes and quotes for CMake
            val = sym.str_value.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'set({name} "{val}")\n')
    with open(path, "w") as f:
        f.writelines(lines)


def write_json(kconf, path):
    """Write sdkconfig.json with Python-typed values."""
    _ensure_dir(path)
    config = {}
    for sym in kconf.unique_defined_syms:
        name = f"CONFIG_{sym.name}"
        if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
            config[name] = sym.str_value == "y"
        elif sym.type == kconfiglib.INT:
            try:
                config[name] = int(sym.str_value)
            except ValueError:
                config[name] = sym.str_value
        elif sym.type == kconfiglib.HEX:
            config[name] = sym.str_value  # keep as "0x..." string
        elif sym.type == kconfiglib.STRING:
            config[name] = sym.str_value
    with open(path, "w") as f:
        json.dump(config, f, indent=2, sort_keys=True)
        f.write("\n")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate VibeRTOS Kconfig output files from a Kconfig tree."
    )
    parser.add_argument("--kconfig",          required=True,
                        help="Path to root Kconfig file")
    parser.add_argument("--config",           required=True,
                        help="Path to sdkconfig (.config) — read/written")
    parser.add_argument("--header",           required=True,
                        help="Output path for autoconf.h")
    parser.add_argument("--cmake",            required=True,
                        help="Output path for sdkconfig.cmake")
    parser.add_argument("--json",             required=True,
                        help="Output path for sdkconfig.json")
    parser.add_argument("--srctree",          required=True,
                        help="Source tree root (resolves Kconfig 'source' paths)")
    parser.add_argument("--board-defconfig",  default=None,
                        help="Board defconfig to seed config when no sdkconfig exists")
    args = parser.parse_args()

    # -----------------------------------------------------------------------
    # Check kconfiglib
    # -----------------------------------------------------------------------
    

    # -----------------------------------------------------------------------
    # Set environment variables that kconfiglib reads
    # -----------------------------------------------------------------------
    # srctree  — root directory for resolving `source` directives
    # KCONFIG_CONFIG — path to the active .config file
    os.environ["srctree"]        = args.srctree
    os.environ["KCONFIG_CONFIG"] = args.config

    # -----------------------------------------------------------------------
    # Load Kconfig tree
    # -----------------------------------------------------------------------
    print(f"[kconfig] loading tree: {args.kconfig}")
    kconf = kconfiglib.Kconfig(args.kconfig, warn_to_stderr=True)

    # -----------------------------------------------------------------------
    # Load configuration values
    # Priority: existing sdkconfig > board defconfig > built-in defaults
    # -----------------------------------------------------------------------
    if os.path.exists(args.config):
        print(f"[kconfig] loading config: {args.config}")
        kconf.load_config(args.config)
    elif args.board_defconfig and os.path.exists(args.board_defconfig):
        print(f"[kconfig] seeding from board defconfig: {args.board_defconfig}")
        kconf.load_config(args.board_defconfig)
    else:
        print("[kconfig] no config found — using built-in defaults")
        # load_config with no args applies symbol defaults
        kconf.load_config()

    # -----------------------------------------------------------------------
    # Write outputs
    # -----------------------------------------------------------------------
    print(f"[kconfig] writing sdkconfig  -> {args.config}")
    write_sdkconfig(kconf, args.config)

    print(f"[kconfig] writing autoconf.h -> {args.header}")
    write_autoconf(kconf, args.header)

    print(f"[kconfig] writing cmake      -> {args.cmake}")
    write_cmake(kconf, args.cmake)

    print(f"[kconfig] writing json       -> {args.json}")
    write_json(kconf, args.json)

    print("[kconfig] done.")


if __name__ == "__main__":
    main()
