# kconfig.cmake
# CMake integration for the Kconfig configuration system.
# Runs the kconfig tool and generates include/generated/autoconf.h from .config.

cmake_minimum_required(VERSION 3.20)

# --- Paths ---
set(KCONFIG_ROOT     ${VIBE_RTOS_ROOT}/Kconfig)
set(KCONFIG_CONFIG   ${CMAKE_BINARY_DIR}/.config)
set(KCONFIG_AUTOCONF ${CMAKE_BINARY_DIR}/include/generated/autoconf.h)
set(KCONFIG_HEADER   ${CMAKE_BINARY_DIR}/include/generated/kconfig.h)

# Create the generated include directory
file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/include/generated)

# --- Locate Kconfig tools ---
# Prefer the Python-based kconfiglib (pip install kconfiglib)
find_program(KCONFIG_TOOL menuconfig
    NAMES menuconfig kconfiglib guiconfig
    DOC "Kconfig configuration tool")

find_program(GENCONFIG_TOOL genconfig
    DOC "genconfig tool from kconfiglib")

# --- Functions ---

# vibe_kconfig_generate()
#
# Reads the .config file (or defconfig) and generates autoconf.h.
# If no .config exists, writes a minimal default.
function(vibe_kconfig_generate)
    if(EXISTS ${KCONFIG_CONFIG})
        message(STATUS "Kconfig: using existing .config at ${KCONFIG_CONFIG}")
    else()
        message(STATUS "Kconfig: no .config found — generating minimal default")
        vibe_kconfig_write_default()
    endif()

    # Generate autoconf.h from .config by parsing it in CMake
    vibe_kconfig_parse_to_header(${KCONFIG_CONFIG} ${KCONFIG_AUTOCONF})

    message(STATUS "Kconfig: generated ${KCONFIG_AUTOCONF}")
endfunction()

# vibe_kconfig_write_default()
#
# Writes a minimal default .config with safe defaults.
function(vibe_kconfig_write_default)
    file(WRITE ${KCONFIG_CONFIG}
"# VibeRTOS minimal default configuration
CONFIG_ARCH_ARM=y
CONFIG_CPU_CORTEX_M0PLUS=y
CONFIG_BOARD_RPI_PICO=y
CONFIG_SOC_RP2040=y
CONFIG_KERNEL_PREEMPT_ENABLED=y
CONFIG_NUM_PRIORITIES=32
CONFIG_TIMESLICE_MS=10
CONFIG_TICKLESS_IDLE=y
CONFIG_SMP=n
CONFIG_HEAP_MEM=y
CONFIG_HEAP_SIZE=4096
CONFIG_STACK_CANARY=y
CONFIG_TLS=y
CONFIG_SCHED_DYNAMIC_PRIORITY=y
CONFIG_SYS_CLOCK_HZ=1000
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=2
CONFIG_LOG_BACKEND_UART=y
CONFIG_SHELL=y
CONFIG_UART=y
CONFIG_GPIO=y
")
endfunction()

# vibe_kconfig_parse_to_header(config_file output_header)
#
# Parses a Kconfig .config file and produces a C header with #define macros.
function(vibe_kconfig_parse_to_header CONFIG_FILE OUTPUT_HEADER)
    # Read the .config file
    file(STRINGS ${CONFIG_FILE} CONFIG_LINES)

    set(HEADER_CONTENT "/* Auto-generated by kconfig.cmake — do not edit */\n")
    set(HEADER_CONTENT "${HEADER_CONTENT}#ifndef VIBE_AUTOCONF_H\n")
    set(HEADER_CONTENT "${HEADER_CONTENT}#define VIBE_AUTOCONF_H\n\n")

    foreach(LINE ${CONFIG_LINES})
        # Skip blank lines and comments
        if(LINE MATCHES "^#" OR LINE MATCHES "^$")
            continue()
        endif()

        # CONFIG_FOO=y -> #define CONFIG_FOO 1
        if(LINE MATCHES "^(CONFIG_[A-Za-z0-9_]+)=y$")
            set(HEADER_CONTENT "${HEADER_CONTENT}#define ${CMAKE_MATCH_1} 1\n")

        # CONFIG_FOO=n -> /* CONFIG_FOO is not set */
        elseif(LINE MATCHES "^(CONFIG_[A-Za-z0-9_]+)=n$")
            set(HEADER_CONTENT "${HEADER_CONTENT}/* ${CMAKE_MATCH_1} is not set */\n")

        # CONFIG_FOO="string" -> #define CONFIG_FOO "string"
        elseif(LINE MATCHES "^(CONFIG_[A-Za-z0-9_]+)=\"(.*)\"$")
            set(HEADER_CONTENT "${HEADER_CONTENT}#define ${CMAKE_MATCH_1} \"${CMAKE_MATCH_2}\"\n")

        # CONFIG_FOO=123 -> #define CONFIG_FOO 123
        elseif(LINE MATCHES "^(CONFIG_[A-Za-z0-9_]+)=([0-9]+)$")
            set(HEADER_CONTENT "${HEADER_CONTENT}#define ${CMAKE_MATCH_1} ${CMAKE_MATCH_2}\n")

        # CONFIG_FOO=0x... -> #define CONFIG_FOO 0x...
        elseif(LINE MATCHES "^(CONFIG_[A-Za-z0-9_]+)=(0x[0-9A-Fa-f]+)$")
            set(HEADER_CONTENT "${HEADER_CONTENT}#define ${CMAKE_MATCH_1} ${CMAKE_MATCH_2}\n")
        endif()
    endforeach()

    set(HEADER_CONTENT "${HEADER_CONTENT}\n#endif /* VIBE_AUTOCONF_H */\n")

    file(WRITE ${OUTPUT_HEADER} ${HEADER_CONTENT})
endfunction()

# Run generation at configure time
vibe_kconfig_generate()

# Add generated directory to include path
include_directories(${CMAKE_BINARY_DIR}/include/generated)
